FROM golang:1.18 AS build
WORKDIR /server/
COPY . .
ENV CGO_ENABLED=0
ENV GO111MODULE=on
ENV GOPROXY=https://goproxy.cn,direct
RUN GOOS=linux go build -installsuffix cgo -o httpserver main.go

FROM busybox
COPY --from=build /server/httpserver /server/httpserver
EXPOSE 8360
ENV ENV local
WORKDIR /server/
ENTRYPOINT ["./httpserver"]